language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - npm ci

# Scripts to be run such as tests
before_script:
  - echo "no tests"
  
script:
  - npm run build
  - docker --version # print the version for logging
  - docker build -t udagram_feed_api .
  - docker tag udagram_feed_api forsythetony/udagram_feed_api:${TRAVIS_COMMIT::8}

after_success:
  - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  - docker push forsythetony/udagram_feed_api:${TRAVIS_COMMIT::8}
